name: 'Add label to gh issue'
description: 'Add label to gh issue'
inputs:
  token:
    description: 'GitHub access token'
    required: true
  issueNumber:
    description: 'Id of issue'
    required: true
  labels:
    description: 'New labels'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'